apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: serviceonboardings.portal.itlusions.com
spec:
  group: portal.itlusions.com
  names:
    kind: ServiceOnboarding
    plural: serviceonboardings
    singular: serviceonboarding
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                serviceName:
                  type: string
                  description: "Name of the Portal service."
                namespace:
                  type: string
                  description: "Namespace where the service resides."
                customerId:
                  type: string
                  description: "ID of the customer owning the service."
                onboardingStatus:
                  type: string
                  enum:
                    - discovered
                    - in-progress
                    - failed
                    - completed
                  description: "The current status of the service onboarding."
                metadata:
                  type: object
                  description: "Additional metadata about the service."
