version: "3.8"

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    environment:
      - KUBECONFIG=/config/.kube/config
    volumes:
      - ~/.kube:/config/.kube
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
