apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gzip
spec:
  compress:
    defaultEncoding: gzip
    includedContentTypes:
      - application/json
      - text/html
      - text/plain